Parameters:
  BucketName:
    Type: String
  EnvironmentName:
    Type: String
    Description: The name of the environment this loaded spotify data belongs to

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Join [ "-", [!Ref EnvironmentName, !Ref BucketName] ]
      Tags:
        - Key: Name
          Value: !Ref BucketName