AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: !Join [ "-", ["cf-packages" ,!Ref AWS::Region, !Ref AWS::StackId] ]
      Tags:
        - Key: Name
          Value: cf-packages